name = "url2image-worker"
main = "worker/index.js"
compatibility_date = "2025-04-06"

[build]
command = "rm -rf node_modules && npm install -g @cloudflare/wrangler && cd frontend && npm ci && npm run build"
compatibility_flags = ["nodejs_compat"]
watch_dir = "frontend"

[wasm_modules]
steg = "worker/wasm_steg_bg.wasm"

[[routes]]
pattern = "api.3815147.ip-ddns.com/*"
zone_name = "3815147.ip-ddns.com"

[env]
# 显式指定安装路径
PATH = "/usr/local/bin:${PATH}"

[env.production]
account_id = "your_account_id"
workers_dev = true
