name = "url2image-worker"
main = "./worker/index.js"
compatibility_date = "2025-04-06"

[build]
command = "cd frontend && npm install && npm run build"
upload.format = "service-pack"
watch_dir = "frontend"

[wasm_modules]
steg = "worker/wasm_steg_bg.wasm"

[[routes]]
pattern = "api.3815147.ip-ddns.com/*"
zone_name = "3815147.ip-ddns.com"
