name = "url2image-worker"
main = "worker/index.js"
compatibility_date = "2025-04-06"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && npm ci && npm run build"
watch_dir = "frontend"

[wasm_modules]
steg = "worker/wasm_steg_bg.wasm"

[[routes]]
pattern = "api.3815147.ip-ddns.com/*"
zone_name = "3815147.ip-ddns.com"

[env.production]
account_id = "5439bb392e8ce94c6683944cbcc1e61a"  # 替换为你的 Cloudflare 账户 ID
workers_dev = false

[env.development]
workers_dev = true
