name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 安装 Node.js 和依赖
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd frontend
          npm install
          npm run build

      # 安装 wrangler 并部署到 Cloudflare
      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Deploy Worker
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
